In [1]:
import torch

In [2]:
vector1 = torch.tensor([1.,2.,3.])
print(vector1)

tensor([1., 2., 3.])


In [3]:
vector2= torch.tensor([4.,5.,6.])
print(vector2)

tensor([4., 5., 6.])


In [4]:
add_vector=vector1+vector2
print(add_vector)

tensor([5., 7., 9.])


In [5]:
sub_vector=vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [6]:
torch.mul(vector1,vector2)

tensor([ 4., 10., 18.])

In [7]:
torch.div(vector1,vector2)

tensor([0.2500, 0.4000, 0.5000])

In [8]:
torch.dot(vector1,vector2)

tensor(32.)